// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {context} from '../models';

export function CreateByokPolicy(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function DeleteCloudCombo(arg1:string):Promise<void>;

export function FetchByokPolicies():Promise<Array<{[key: string]: any}>>;

export function FetchCloudBilling():Promise<auth.CloudBilling>;

export function FetchCloudCombos():Promise<Array<auth.CloudUserCombo>>;

export function FetchCloudModelStats():Promise<Array<auth.CloudModelStatsEntry>>;

export function FetchCloudOptimizationConfig():Promise<string>;

export function FetchCloudUsage():Promise<auth.CloudUsage>;

export function FetchFreeChannels(arg1:context.Context):Promise<Array<{[key: string]: any}>>;

export function FetchOfficialComboTemplates(arg1:context.Context):Promise<Array<auth.CloudComboTemplate>>;

export function FetchPlans():Promise<Array<auth.CloudPlan>>;

export function FetchPlatformChannels(arg1:context.Context):Promise<Array<{[key: string]: any}>>;

export function FetchProviderHealthMetrics(arg1:string):Promise<Array<{[key: string]: any}>>;

export function FetchProviderHealthSummary():Promise<Array<{[key: string]: any}>>;

export function FetchRecommendedCombos():Promise<Array<auth.CloudCombo>>;

export function GetAuthState():Promise<auth.AuthInfo>;

export function GetPlatformToken():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function PlatformAPIBaseURL():Promise<string>;

export function PushCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:{[key: string]: any},arg8:Array<number>):Promise<auth.CloudUserCombo>;

export function PushCloudOptimizationConfig(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncCloudCombosToLocal():Promise<Array<auth.CloudUserCombo>>;

export function UpdateCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:{[key: string]: any},arg9:Array<number>):Promise<void>;
