// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';
import {config} from '../models';
import {auth} from '../models';
import {usage} from '../models';
import {presets} from '../models';
import {sessions} from '../models';
import {sync} from '../models';
import {logs} from '../models';
import {mcp} from '../models';
import {prompts} from '../models';
import {skills} from '../models';
import {mitm} from '../models';

export function AddMITMRule(arg1:string):Promise<void>;

export function ApplyComboOptimization(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ApplyComboSortPreset(arg1:string,arg2:string):Promise<void>;

export function ApplyPromptPreset(arg1:string,arg2:string):Promise<void>;

export function ApplyRecommendation(arg1:string,arg2:string):Promise<void>;

export function ChatCompletion(arg1:Array<{[key: string]: any}>,arg2:string):Promise<{[key: string]: any}>;

export function ChatCompletionForChannel(arg1:string,arg2:Array<{[key: string]: any}>,arg3:string):Promise<{[key: string]: any}>;

export function CheckUpdate():Promise<{[key: string]: any}>;

export function ClearLogs():Promise<void>;

export function ConfirmAction(arg1:string,arg2:string):Promise<boolean>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateCheckoutSession(arg1:string,arg2:Array<number>):Promise<{[key: string]: any}>;

export function DeleteCloudCombo(arg1:string):Promise<void>;

export function DeleteComboTemplate(arg1:string):Promise<void>;

export function DeleteCustomChannel(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteModelCombo(arg1:string):Promise<void>;

export function DeletePromptPreset(arg1:string,arg2:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DiscoverModels(arg1:string):Promise<Array<discovery.DiscoveredModel>>;

export function ExchangeOAuthCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ExportConfig():Promise<string>;

export function FetchCloudCombos():Promise<Array<{[key: string]: any}>>;

export function FetchModelStats():Promise<Array<{[key: string]: any}>>;

export function FetchModelsFromURL(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetAppInfo():Promise<{[key: string]: any}>;

export function GetAuthState():Promise<auth.AuthInfo>;

export function GetByokPolicies():Promise<Array<{[key: string]: any}>>;

export function GetCloudBilling():Promise<{[key: string]: any}>;

export function GetCloudUsage():Promise<{[key: string]: any}>;

export function GetComboByName(arg1:string):Promise<config.ModelCombo>;

export function GetComboRouteMetrics():Promise<Array<{[key: string]: any}>>;

export function GetDailyUsage(arg1:number):Promise<Array<usage.DailyUsage>>;

export function GetDefaultComboName():Promise<string>;

export function GetLocalAccessToken():Promise<string>;

export function GetLocale():Promise<string>;

export function GetMITMEnvHint():Promise<{[key: string]: string}>;

export function GetMITMRecentIntercepts(arg1:number):Promise<Array<{[key: string]: any}>>;

export function GetMITMRules():Promise<Array<string>>;

export function GetMITMStatus():Promise<{[key: string]: any}>;

export function GetOAuthConnections():Promise<Array<{[key: string]: any}>>;

export function GetOAuthProviders():Promise<Array<{[key: string]: any}>>;

export function GetOAuthToken(arg1:string):Promise<string>;

export function GetOfficialComboTemplates():Promise<Array<{[key: string]: any}>>;

export function GetOptimizationConfig():Promise<{[key: string]: any}>;

export function GetOptimizationPlan(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetPlans():Promise<Array<{[key: string]: any}>>;

export function GetPlatformAPIBaseURL():Promise<string>;

export function GetPlatformToken():Promise<string>;

export function GetPresetByName(arg1:string):Promise<presets.ProviderPreset>;

export function GetProviderHealthMetrics(arg1:string):Promise<Array<{[key: string]: any}>>;

export function GetProviderHealthSummary():Promise<Array<{[key: string]: any}>>;

export function GetQuickStrategies():Promise<Array<{[key: string]: any}>>;

export function GetRecommendedCombos():Promise<Array<{[key: string]: any}>>;

export function GetRelayGateways():Promise<Array<{[key: string]: any}>>;

export function GetRuntimeStatus():Promise<{[key: string]: any}>;

export function GetSelectedRelayGateway():Promise<string>;

export function GetSession(arg1:string,arg2:string):Promise<sessions.Session>;

export function GetSessionMessages(arg1:string,arg2:string):Promise<Array<sessions.Message>>;

export function GetSyncConfig():Promise<sync.SyncConfig>;

export function GetSyncStatus():Promise<sync.SyncStatus>;

export function GetTaskProfiles():Promise<Array<{[key: string]: any}>>;

export function GetTotalUsage():Promise<{[key: string]: any}>;

export function GetTunnelStatus():Promise<{[key: string]: any}>;

export function GetTunnelURL():Promise<string>;

export function GetUsageSummary():Promise<{[key: string]: any}>;

export function HandleDeepLink(arg1:string):Promise<void>;

export function ImportConfig(arg1:string):Promise<void>;

export function ImportCustomPreset(arg1:Array<number>):Promise<void>;

export function InstallSkillFromGitHub(arg1:string,arg2:string):Promise<void>;

export function InstallSkillFromLocal(arg1:string,arg2:string):Promise<void>;

export function IsMITMRunning():Promise<boolean>;

export function IsTunnelRunning():Promise<boolean>;

export function ListChannels():Promise<Array<config.Channel>>;

export function ListComboTemplates():Promise<Array<config.ModelCombo>>;

export function ListLogs(arg1:number,arg2:number):Promise<Array<logs.RequestLog>>;

export function ListLogsFiltered(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Array<logs.RequestLog>>;

export function ListMCPServers():Promise<Array<mcp.MCPServer>>;

export function ListModelCombos():Promise<Array<config.ModelCombo>>;

export function ListModelPricing():Promise<Array<usage.ModelPricing>>;

export function ListPresetsByCategory(arg1:string):Promise<Array<presets.ProviderPreset>>;

export function ListPromptPresets():Promise<Array<prompts.PromptPreset>>;

export function ListProviderPresets():Promise<Array<presets.ProviderPreset>>;

export function ListSessions(arg1:string,arg2:number):Promise<Array<sessions.Session>>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PerformUpdate():Promise<void>;

export function PreviewComboOptimization(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function PushCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:{[key: string]: any},arg8:string):Promise<{[key: string]: any}>;

export function ReadCurrentPrompt(arg1:string):Promise<string>;

export function RecordUsage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveMITMRule(arg1:string):Promise<void>;

export function RenameComboTemplate(arg1:string,arg2:string):Promise<void>;

export function ReorderChannels(arg1:Array<string>):Promise<void>;

export function ResetLocalAccessToken():Promise<string>;

export function RevokeOAuthToken(arg1:string):Promise<void>;

export function SaveComboTemplate(arg1:config.ModelCombo):Promise<void>;

export function SaveCustomChannel(arg1:config.Channel):Promise<string>;

export function SaveMCPServer(arg1:mcp.MCPServer):Promise<void>;

export function SaveModelCombo(arg1:config.ModelCombo):Promise<void>;

export function SaveModelPricing(arg1:Array<usage.ModelPricing>):Promise<void>;

export function SavePromptPreset(arg1:prompts.PromptPreset):Promise<void>;

export function SaveRelayGateway(arg1:string):Promise<void>;

export function ScanSkillsDir():Promise<Array<skills.Skill>>;

export function SearchSessions(arg1:string,arg2:string,arg3:number):Promise<Array<sessions.Session>>;

export function SelectDirectory():Promise<string>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function SetByokPolicy(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function SetDefaultComboName(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetMITMManager(arg1:mitm.Manager):Promise<void>;

export function SetOptimizationConfig(arg1:{[key: string]: any}):Promise<void>;

export function SetPlatformAPIBaseURL(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function StartLocalGateway():Promise<void>;

export function StartMITM():Promise<void>;

export function StartOAuthFlow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopLocalGateway():Promise<void>;

export function StopMITM():Promise<void>;

export function StopTunnel():Promise<void>;

export function SyncCustomChannelsToCloud(arg1:Array<{[key: string]: any}>):Promise<{[key: string]: any}>;

export function SyncLocalDataToCloud():Promise<void>;

export function SyncOptimizationConfigFromCloud():Promise<{[key: string]: any}>;

export function SyncOptimizationConfigToCloud():Promise<void>;

export function SyncPlatformChannels():Promise<void>;

export function SyncPull():Promise<void>;

export function SyncPush():Promise<void>;

export function TestChannelDirect(arg1:string):Promise<{[key: string]: any}>;

export function TestCustomChannel(arg1:string):Promise<{[key: string]: any}>;

export function TestMITMDomain(arg1:string):Promise<{[key: string]: any}>;

export function TestRelayGateway(arg1:string):Promise<{[key: string]: any}>;

export function ToggleMCPServer(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSkill(arg1:string,arg2:boolean):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;

export function UpdateCloudCombo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:{[key: string]: any},arg9:string):Promise<void>;

export function UpdateDefaultModel(arg1:string,arg2:string):Promise<void>;

export function UpdateRoutingSettings(arg1:string,arg2:number):Promise<void>;

export function UpdateSyncConfig(arg1:sync.SyncConfig):Promise<void>;
